api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    eager_loading:
        enabled: true
    collection:
        order_parameter_name: 'order'
        pagination:
            client_enabled: true
            enabled: true
            page_parameter_name: page
            enabled_parameter_name: pagination
            items_per_page: 10
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 20
            partial: true
            client_partial: true
            partial_parameter_name: 'partial'
